kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cotd-development
spec:
  template:
    metadata:
      labels:
        app: cotd
        env: development
    spec:
      containers:
      - name: cotd
        image: stefanopicozzi/cotd
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
