# cotd Service
apiVersion: v1
kind: Service
metadata:
  name: cotd
  labels:
    app: cotd
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
    nodePort: 30181
  selector:
    app: cotd
